In [1]:
import pandas as pd

In [7]:
tickets = pd.read_csv("data_safe_copy.csv",index_col=0)
tickets.head()

                  opened_at   category priority resolution_minutes
ticket_id
TK-0001    2024-03-01 09:00    billing      low                 45
TK-0002    2024-03-01 09:30    account   medium                 30
TK-0003    2024-03-01 10:00  technical     high                 75
TK-0004    2024-03-01 10:30    billing      low                NaN
TK-0005    2024-03-01 11:00    account   medium            unknown

In [8]:
tickets.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, TK-0001 to TK-0500
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   opened_at           500 non-null    object
 1   category            500 non-null    object
 2   priority            500 non-null    object
 3   resolution_minutes  450 non-null    object
dtypes: object(4)
memory usage: 19.5+ KB

In [17]:
#t2 means task 2
tickets_t2 = tickets.copy()
tickets_t2['opened_at'] = pd.to_datetime(tickets_t2['opened_at'])
tickets_t2.head()

                    opened_at   category priority resolution_minutes
ticket_id
TK-0001   2024-03-01 09:00:00    billing      low                 45
TK-0002   2024-03-01 09:30:00    account   medium                 30
TK-0003   2024-03-01 10:00:00  technical     high                 75
TK-0004   2024-03-01 10:30:00    billing      low                NaN
TK-0005   2024-03-01 11:00:00    account   medium            unknown

In [16]:
tickets_t2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, TK-0001 to TK-0500
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   opened_at           500 non-null    datetime64[ns]
 1   category            500 non-null    object
 2   priority            500 non-null    object
 3   resolution_minutes  450 non-null    object
dtypes: datetime64[ns](1), object(3)
memory usage: 35.7+ KB

In [19]:
tickets_t2['category'] = tickets_t2['category'].str.lower().str.strip()
tickets_t2['category'].unique()

array(['billing', 'account', 'technical'], dtype=object)

In [20]:
tickets_t2['priority'] = tickets_t2['priority'].str.lower().str.strip()
tickets_t2['priority'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [48]:
#task3
tickets_t3 = tickets_t2.copy()
na_values = "unknown"
tickets_t3['resolution_minutes'] = pd.to_numeric(tickets_t3['resolution_minutes'], errors='coerce')
print(tickets_t3.isnull().sum())
print(tickets['resolution_minutes'].isnull().sum())
print((tickets['resolution_minutes'] == 'unknown').sum())
tickets_t3

opened_at               0
category                0
priority                0
resolution_minutes    100
dtype: int64
50
50

                    opened_at   category priority  resolution_minutes
ticket_id
TK-0001   2024-03-01 09:00:00    billing      low                45.0
TK-0002   2024-03-01 09:30:00    account   medium                30.0
TK-0003   2024-03-01 10:00:00  technical     high                75.0
TK-0004   2024-03-01 10:30:00    billing      low                 NaN
TK-0005   2024-03-01 11:00:00    account   medium                 NaN
...                       ...        ...      ...                 ...
TK-0496   2024-03-01 11:30:00  technical     high                60.0
TK-0497   2024-03-01 12:00:00    billing     high                15.0
TK-0498   2024-03-01 12:30:00    account      low                90.0
TK-0499   2024-03-01 13:00:00  technical   medium               120.0
TK-0500   2024-03-01 13:30:00    billing   medium                25.0

[500 rows x 4 columns]

In [42]:
#task4
tickets_clean = tickets_t3.copy()
tickets_clean.dropna(subset=['resolution_minutes'], inplace=True)
print(tickets_clean.isnull().sum())

opened_at             0
category              0
priority              0
resolution_minutes    0
dtype: int64

In [43]:
#task 4 verification
print(tickets_t3.shape[0])
print(tickets_clean.shape[0])
print((tickets_clean['resolution_minutes'] < 0).any())
print("Unique Categories:")
print(tickets_clean['category'].unique())

print("\nUnique Priorities:")
print(tickets_clean['priority'].unique())

500
400
False
Unique Categories:
['billing' 'account' 'technical']

Unique Priorities:
['low' 'medium' 'high']

In [ ]:
#task5
total = len(tickets)
clean = len(tickets_clean)
missing = tickets['resolution_minutes'].isna().sum()+(tickets['resolution_minutes'] == 'unknown').sum()
avg_res = tickets_clean['resolution_minutes'].mean()
max_res = tickets_clean['resolution_minutes'].max()

summary = {
    'total_records': total,
    'clean_records': clean,
    'missing_resolution': missing,
    'avg_resolution': avg_res,
    'max_resolution': max_res
}

print("Summary Metrics:")
print(summary)

verification_check = (summary['clean_records'] + summary['missing_resolution']) == summary['total_records']

print("\nVerification Passed:", verification_check)

Summary Metrics:
{'total_records': 500, 'clean_records': 400, 'missing_resolution': np.int64(100), 'avg_resolution': np.float64(57.5), 'max_resolution': 120.0}

Verification Passed: True